# Generated by Django 4.2.3 on 2023-08-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='popular_blogs',
            new_name='blogs',
        ),
        migrations.DeleteModel(
            name='regular_blogs',
        ),
    ]
