# Generated by Django 4.2.3 on 2023-08-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_categories_alter_blogs_title_contact_usdb_catagory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_usdb',
            name='catagory',
        ),
        migrations.AddField(
            model_name='blogs',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.categories'),
        ),
    ]
