# Generated by Django 4.2.3 on 2023-08-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_contact_usdb_catagory_blogs_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
